version: "3.7"

services:
    mysql:
        image: mysql:5.7
        volumes:
            - ~/otb/db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
    wordpress:
        depends_on:
            - mysql
        image: hardeepasrani/pirate-brewery
        ports:
            - 8889:80
        networks:
            - default
        volumes:
            - ~/wpcore:/var/www/html/
            - .:/var/www/html/wp-content/plugins/logo-maker/
        restart: always
        environment:
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_ROOT_PASSWORD: wordpress
            WORDPRESS_DEBUG: "true"
